# Generated by Django 5.1 on 2024-09-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарии')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now=True, null=True, verbose_name='дата и время последней рассылки')),
                ('status_log', models.CharField(blank=True, max_length=20, null=True, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, max_length=255, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='начало рассылки')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='окончание рассылки')),
                ('periodicity', models.CharField(blank=True, choices=[('once_day', 'раз в день'), ('once_week', 'раз в неделю'), ('once_monthly', 'раз в месяц')], max_length=20, null=True, verbose_name='периодичность')),
                ('status', models.CharField(blank=True, choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], max_length=20, null=True, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_theme', models.TextField(verbose_name='тема письма')),
                ('letter_body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщение',
            },
        ),
    ]
