# Generated by Django 5.1 on 2024-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status_log',
            field=models.CharField(blank=True, choices=[('successfully', 'Успешно'), ('not_successful', 'не успешно')], max_length=20, null=True, verbose_name='статус попытки'),
        ),
    ]
